language: ruby
rvm:
  - "2.1"
  - "2.0"
  - "1.9.3"
  - "rbx-2.2.6"
  - "jruby-1.7.15"
gemfile:
  - "gemfiles/rails_3.1.gemfile"
  - "gemfiles/rails_3.2.gemfile"
  - "gemfiles/rails_4.0.gemfile"
  - "gemfiles/rails_4.1.gemfile"
script: 'bundle exec rake test'
before_install:
  - sudo rm -rf /var/lib/cassandra/*
  - curl -s http://www.us.apache.org/dist/cassandra/2.1.2/apache-cassandra-2.1.2-bin.tar.gz | tar -xvzf - && pkill -f cassandra && sudo sh apache-cassandra-2.1.2/bin/cassandra
bundler_args: '--without=debug'
services:
  - cassandra
matrix:
  allow_failures:
    - rvm: "rbx-2.2.6"
